runtime: java
env: flex

handlers:
  - url: /.*
    script: this field is required, but ignored

automatic_scaling:
  cool_down_period_sec: 180
  target_cpu_utilization: 0.8
  max_concurrent_requests: 80
