runtime: java
env: standard

handlers:
  - url: /.*
    script: this field is required, but ignored

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 4
#  cool_down_period_sec: 180
#  cpu_utilization:
#    target_utilization: 0.6