runtime: java
env: standard

handlers:
  - url: /.*
    script: this field is required, but ignored

automatic_scaling:
  cool_down_period_sec: 180
  target_cpu_utilization: 0.8
  target_throughput_utilization: 0.6
  max_concurrent_requests: 20
  max_instances: 50
